#pour le moment c'est exactememnt la mm config que pour le front. je garde ça au cas ou on veut creer une config spécifique plutard
FROM node

# définit le dossier 'app' comme dossier de travail
WORKDIR /app

# copie 'package.json' et 'package-lock.json' (si disponible)
COPY package*.json ./

# copie les fichiers et dossiers du projet dans le dossier de travail (par exemple : le dossier 'app')
COPY . .

# construit l'app pour la production en la minifiant
RUN npm install

CMD [ "npm", "run", "dev" ]